name: CRM CONSULTING AND BUSINESS AUTOMATION
origin: local
employees: 11-50
company_type: service
website:
  url: ''
description: A consultancy providing CRM implementation and business process automation
  services.
tags:
- service-providers
_meta:
  checked_at: '2026-05-09T23:38:08.783097+00:00'
